/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  avatar: () => import("@/views/_builtin/avatar/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "business_orders_sea-export": () => import("@/views/business/orders/sea-export/index.vue"),
  "business_orders_sea-import": () => import("@/views/business/orders/sea-import/index.vue"),
  "finance_basic-data_currency": () => import("@/views/finance/basic-data/currency/index.vue"),
  "finance_basic-data_stream": () => import("@/views/finance/basic-data/stream/index.vue"),
  "finance_basic-data_subject": () => import("@/views/finance/basic-data/subject/index.vue"),
  home: () => import("@/views/home/index.vue"),
  setting_system_admin: () => import("@/views/setting/system/admin/index.vue"),
  setting_system_company: () => import("@/views/setting/system/company/index.vue"),
  setting_system_menu: () => import("@/views/setting/system/menu/index.vue"),
  setting_system_role: () => import("@/views/setting/system/role/index.vue"),
  warehouse_data_material: () => import("@/views/warehouse/data/material/index.vue"),
  warehouse_data_warehouse: () => import("@/views/warehouse/data/warehouse/index.vue"),
  "warehouse_funds_payment-order": () => import("@/views/warehouse/funds/payment-order/index.vue"),
  "warehouse_funds_receiving-order": () => import("@/views/warehouse/funds/receiving-order/index.vue"),
};
