/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'avatar',
    path: '/avatar',
    component: 'layout.base$view.avatar',
    meta: {
      title: 'avatar',
      i18nKey: 'route.avatar'
    }
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance'
    },
    children: [
      {
        name: 'finance_finance-data',
        path: '/finance/finance-data',
        meta: {
          title: 'finance_finance-data',
          i18nKey: 'route.finance_finance-data'
        },
        children: [
          {
            name: 'finance_finance-data_subject',
            path: '/finance/finance-data/subject',
            component: 'view.finance_finance-data_subject',
            meta: {
              title: 'finance_finance-data_subject',
              i18nKey: 'route.finance_finance-data_subject'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting'
    },
    children: [
      {
        name: 'setting_system',
        path: '/setting/system',
        meta: {
          title: 'setting_system',
          i18nKey: 'route.setting_system'
        },
        children: [
          {
            name: 'setting_system_admin',
            path: '/setting/system/admin',
            component: 'view.setting_system_admin',
            meta: {
              title: 'setting_system_admin',
              i18nKey: 'route.setting_system_admin'
            }
          },
          {
            name: 'setting_system_company',
            path: '/setting/system/company',
            component: 'view.setting_system_company',
            meta: {
              title: 'setting_system_company',
              i18nKey: 'route.setting_system_company'
            }
          },
          {
            name: 'setting_system_menu',
            path: '/setting/system/menu',
            component: 'view.setting_system_menu',
            meta: {
              title: 'setting_system_menu',
              i18nKey: 'route.setting_system_menu'
            }
          },
          {
            name: 'setting_system_role',
            path: '/setting/system/role',
            component: 'view.setting_system_role',
            meta: {
              title: 'setting_system_role',
              i18nKey: 'route.setting_system_role'
            }
          }
        ]
      }
    ]
  }
];
