/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'avatar',
    path: '/avatar',
    component: 'layout.base$view.avatar',
    meta: {
      title: 'avatar',
      i18nKey: 'route.avatar'
    }
  },
  {
    name: 'business',
    path: '/business',
    component: 'layout.base',
    meta: {
      title: 'business',
      i18nKey: 'route.business'
    },
    children: [
      {
        name: 'business_orders',
        path: '/business/orders',
        meta: {
          title: 'business_orders',
          i18nKey: 'route.business_orders'
        },
        children: [
          {
            name: 'business_orders_sea-export',
            path: '/business/orders/sea-export',
            component: 'view.business_orders_sea-export',
            meta: {
              title: 'business_orders_sea-export',
              i18nKey: 'route.business_orders_sea-export'
            }
          },
          {
            name: 'business_orders_sea-import',
            path: '/business/orders/sea-import',
            component: 'view.business_orders_sea-import',
            meta: {
              title: 'business_orders_sea-import',
              i18nKey: 'route.business_orders_sea-import'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance'
    },
    children: [
      {
        name: 'finance_basic-data',
        path: '/finance/basic-data',
        meta: {
          title: 'finance_basic-data',
          i18nKey: 'route.finance_basic-data'
        },
        children: [
          {
            name: 'finance_basic-data_account-subject',
            path: '/finance/basic-data/account-subject',
            component: 'view.finance_basic-data_account-subject',
            meta: {
              title: 'finance_basic-data_account-subject',
              i18nKey: 'route.finance_basic-data_account-subject'
            }
          },
          {
            name: 'finance_basic-data_cost-item',
            path: '/finance/basic-data/cost-item',
            component: 'view.finance_basic-data_cost-item',
            meta: {
              title: 'finance_basic-data_cost-item',
              i18nKey: 'route.finance_basic-data_cost-item'
            }
          },
          {
            name: 'finance_basic-data_currency',
            path: '/finance/basic-data/currency',
            component: 'view.finance_basic-data_currency',
            meta: {
              title: 'finance_basic-data_currency',
              i18nKey: 'route.finance_basic-data_currency'
            }
          },
          {
            name: 'finance_basic-data_stream',
            path: '/finance/basic-data/stream',
            component: 'view.finance_basic-data_stream',
            meta: {
              title: 'finance_basic-data_stream',
              i18nKey: 'route.finance_basic-data_stream'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting'
    },
    children: [
      {
        name: 'setting_system',
        path: '/setting/system',
        meta: {
          title: 'setting_system',
          i18nKey: 'route.setting_system'
        },
        children: [
          {
            name: 'setting_system_admin',
            path: '/setting/system/admin',
            component: 'view.setting_system_admin',
            meta: {
              title: 'setting_system_admin',
              i18nKey: 'route.setting_system_admin'
            }
          },
          {
            name: 'setting_system_company',
            path: '/setting/system/company',
            component: 'view.setting_system_company',
            meta: {
              title: 'setting_system_company',
              i18nKey: 'route.setting_system_company'
            }
          },
          {
            name: 'setting_system_menu',
            path: '/setting/system/menu',
            component: 'view.setting_system_menu',
            meta: {
              title: 'setting_system_menu',
              i18nKey: 'route.setting_system_menu'
            }
          },
          {
            name: 'setting_system_role',
            path: '/setting/system/role',
            component: 'view.setting_system_role',
            meta: {
              title: 'setting_system_role',
              i18nKey: 'route.setting_system_role'
            }
          }
        ]
      },
      {
        name: 'setting_tool',
        path: '/setting/tool',
        meta: {
          title: 'setting_tool',
          i18nKey: 'route.setting_tool'
        },
        children: [
          {
            name: 'setting_tool_generate-record',
            path: '/setting/tool/generate-record',
            component: 'view.setting_tool_generate-record',
            meta: {
              title: 'setting_tool_generate-record',
              i18nKey: 'route.setting_tool_generate-record'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'warehouse',
    path: '/warehouse',
    component: 'layout.base',
    meta: {
      title: 'warehouse',
      i18nKey: 'route.warehouse'
    },
    children: [
      {
        name: 'warehouse_data',
        path: '/warehouse/data',
        meta: {
          title: 'warehouse_data',
          i18nKey: 'route.warehouse_data'
        },
        children: [
          {
            name: 'warehouse_data_material',
            path: '/warehouse/data/material',
            component: 'view.warehouse_data_material',
            meta: {
              title: 'warehouse_data_material',
              i18nKey: 'route.warehouse_data_material'
            }
          },
          {
            name: 'warehouse_data_warehouse',
            path: '/warehouse/data/warehouse',
            component: 'view.warehouse_data_warehouse',
            meta: {
              title: 'warehouse_data_warehouse',
              i18nKey: 'route.warehouse_data_warehouse'
            }
          }
        ]
      },
      {
        name: 'warehouse_funds',
        path: '/warehouse/funds',
        meta: {
          title: 'warehouse_funds',
          i18nKey: 'route.warehouse_funds'
        },
        children: [
          {
            name: 'warehouse_funds_payment-order',
            path: '/warehouse/funds/payment-order',
            component: 'view.warehouse_funds_payment-order',
            meta: {
              title: 'warehouse_funds_payment-order',
              i18nKey: 'route.warehouse_funds_payment-order'
            }
          },
          {
            name: 'warehouse_funds_receiving-order',
            path: '/warehouse/funds/receiving-order',
            component: 'view.warehouse_funds_receiving-order',
            meta: {
              title: 'warehouse_funds_receiving-order',
              i18nKey: 'route.warehouse_funds_receiving-order'
            }
          }
        ]
      }
    ]
  }
];
